trigger: none

resources:
  repositories:
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools

stages:
- template: shared.yml

# The Prerelease and Release stages are conditioned on whether we are building a pull request and the branch.
- ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
  - template: pipelines/stages/archetype-java-release.yml@azure-sdk-build-tools
    parameters:
      DependsOn: Build
      ArtifactName: packages
      Artifacts:
        - name: azure-internet-analyzer-java
          safeName: internetanalyzer
          stagingProfileId: 534d15ee3800f4
