trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

stages:
- template: shared.yml
